### ISSUE TITLE
Processor/Thread Limitation?

### ISSUE THREAD

**Issue by eesnyder** [ronen25/panorama#5]
I am running Ubuntu on an AMD Ryzen 7 2700 8-core, 16-thread processor.  When looking at the CPU panel, it correctly identifies the number of cores and threads.  However, only the first 10 CPU graphs appear to be active/functional.  CPUs 11, 13 and 15 are all flat-lined at 0%; CPUs 12, 14 and 16 are pegged at 100%.  They never change.  If you compare the traces with the the gnome-system-monitor, it is clear that CPUs 12, 14 and 16 are not running at 100%:
![screenshot from 2018-10-10 13-48-02](https://user-images.githubusercontent.com/6404909/46765715-94e40e00-cc94-11e8-98a6-078347548232.png)
If this problem is already known and/or documented, I apologize for not doing my research.  However, if it is new, I thought you'd like to know about it.
I am curious where the app gets its information on CPU/thread usage.  I'd be happy to help you debug this if it is a platform specific problem.

**Comment by ronen25** [comment]
@eesnyder Looks like a bug in the code that's reading `/etc/proc/cpuinfo`... From a quick
glance at the code, I suspect it's not handling two-digit CPU identifiers well.
What you're seeing in the graphs for CPUs 10-16 is probably just garbage values.

I'll work on a fix this weekend (Israel's weekend is Friday-Saturday, October 12-13th).
Thank you so much for the detailed bug report, and apologies for the great inconvenience!

**Comment by ronen25** [comment]
@eesnyder I've changed the fetching of the CPU usage, it should work properly now.
I'll be more than glad if you could compile the `1.2.3-dev` branch and see if that issue has indeed resolved.

Thank you for your patience, and apologies for the inconvenience!

**Comment by ronen25** [comment]
Final fix committed into 1.4.0.
