### ISSUE TITLE
libcap-dev required

### ISSUE THREAD

**Issue by zchrissirhcz** [ronen25/panorama#7]
Hi, panorama author

I'm on ubuntu 20.04, failed to use the snap installed panorama, thus I compile it from source.

It failed to compile with error message:
> fatal error: 'sys/capability.h' file not found

The solution is
>sudo apt-get install libcap-dev

Hope this can be helpful to others, and may consider add it in the readme.

**Comment by ronen25** [comment]
Hi @zchrissirhcz, thank you for your comment! `libcap-dev` is mentioned in the Wiki page, it is linked in the Readme: https://github.com/ronen25/panorama/wiki/Compiling-from-Source
